# EXAMPLE, replaced in CI with actual secrets

# SSH Access
auser: "ubuntu"
assh_private_key_file: "~/.ssh/id_homelab"
master1_ip: "192.168.1.10"
worker1_ip: "192.168.1.11"

# k3s
k3s_token: "K10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx::server:xxxxxxxx"

# Application passwords
grafana_admin_password: "superSecureGrafanaPass2026"
argocd_admin_password: "argocdStrongPass123!"
registry_htpasswd: "admin:$2y$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# GitHub Actions / GitLab CI
github_ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn
  ...
  -----END OPENSSH PRIVATE KEY-----
github_token: "github_pat_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
gitlab_token: "glpat-XXXXXXXXXXXXXXXXXXXX"

# TLS/HTTPS (self-signed or Let's Encrypt)
tls_email: "admin@homelab.local"
wildcard_domain: "*.homelab.local"
