image:
  tag: "3.1.2"
service:
  type: LoadBalancer
  spec:
    externalIPs:
      - "192.168.1.10"
ports:
  web: { port: 80, exposedPort: 80 }
  websecure: { port: 443, exposedPort: 443 }
providers:
  kubernetesCRD: { enabled: true }
  kubernetesIngress: { enabled: true }
dashboard:
  enabled: true
  ingress:
    enabled: true
    hosts: [{ host: traefik.local, paths: [{ path: /, pathType: Prefix }] }]
persistence:
  enabled: true
  size: 1Gi
