- name: Install k3s agent
  shell: |
    curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} \
    K3S_URL=https://{{ groups['k3s_server'][0] }}:6443 sh -
  args:
    creates: /usr/local/bin/k3s-agent

- name: Enable k3s-agent service
  systemd:
    name: k3s-agent
    enabled: yes
    state: started
